Feature: UPPERCASE FEATURE
  GIVEN AN UPPERCASE DESCRIPTION

  Background: UPPERCASE BACKGROUND
  UPPERCASE BACKGROUND DESCRIPTION
    Given UPPERCASE BACKGROUND STEP
    And MixedCase step

  Scenario: UPPERCASE SCENARIO
  UPPERCASE SCENARIO DESCRIPTION
    Given UPPERCASE STEP
    And MixedCase step

  Scenario Outline: UPPERCASE SCENARIO OUTLINE
  UPPERCASE SCENARIO OUTLINE DESCRIPTION
    Given UPPERCASE STEP
    And MixedCase step

    Examples: UPPERCASE EXAMPLE
    UPPERCASE EXAMPLE DESCRIPTION
      | MixedCase head  | UPPERCASE HEADER | mixed HEAD  | UC HEADER MC VALUES   | MC header UP values   |
      | MixedCase Value | UPPERCASE VALUE  | MIXED value | MC value in UC header | UP VALUE IN MC HEADER |

  Rule: UPPERCASE RULE
  UPPERCASE RULE DESCRIPTION

    Background: UPPERCASE BACKGROUND IN RULE
      UPPERCASE BACKGROUND DESCRIPTION IN RULE
      Given MixedCase step
      And UPPERCASE STEP

    Scenario: UPPERCASE SCENARIO IN RULE
    UPPERCASE SCENARIO DESCRIPTION IN RULE
      Given MixedCase step
      And UPPERCASE STEP
